#ifndef OL_ZIP_API_H
#define OL_ZIP_API_H

#ifdef __cplusplus
extern "C" {
#endif


typedef enum
{
    OL_ZIP_FS_ERROR = -1,
    OL_ZIP_NO_ERROR,
    OL_ZIP_UNDEFINED_ERROR,
    OL_ZIP_TOO_MANY_FILES,
    OL_ZIP_FILE_TOO_LARGE,
    OL_ZIP_UNSUPPORTED_METHOD,
    OL_ZIP_UNSUPPORTED_ENCRYPTION,
    OL_ZIP_UNSUPPORTED_FEATURE,
    OL_ZIP_FAILED_FINDING_CENTRAL_DIR,
    OL_ZIP_NOT_AN_ARCHIVE,
    OL_ZIP_INVALID_HEADER_OR_CORRUPTED,
    OL_ZIP_UNSUPPORTED_MULTIDISK,
    OL_ZIP_DECOMPRESSION_FAILED,
    OL_ZIP_COMPRESSION_FAILED,
    OL_ZIP_UNEXPECTED_DECOMPRESSED_SIZE,
    OL_ZIP_CRC_CHECK_FAILED,
    OL_ZIP_UNSUPPORTED_CDIR_SIZE,
    OL_ZIP_ALLOC_FAILED,
    OL_ZIP_FILE_OPEN_FAILED,
    OL_ZIP_FILE_CREATE_FAILED,
    OL_ZIP_FILE_WRITE_FAILED,
    OL_ZIP_FILE_READ_FAILED,
    OL_ZIP_FILE_CLOSE_FAILED,
    OL_ZIP_FILE_SEEK_FAILED,
    OL_ZIP_FILE_STAT_FAILED,
    OL_ZIP_INVALID_PARAMETER,
    OL_ZIP_INVALID_FILENAME,
    OL_ZIP_BUF_TOO_SMALL,
    OL_ZIP_INTERNAL_ERROR,
    OL_ZIP_FILE_NOT_FOUND,
    OL_ZIP_ARCHIVE_TOO_LARGE,
    OL_ZIP_VALIDATION_FAILED,
    OL_ZIP_WRITE_CALLBACK_FAILED,
    OL_ZIP_TOTAL_ERRORS
} ol_zip_error;

#ifdef __cplusplus
}
#endif

typedef int mz_bool;

mz_bool ol_file_unzip(const char *zip_filename, const char *extract_dir);

#endif
