#------------------------------------------------------------
# (C) Copyright [2006-2008] Marvell International Ltd.
# All Rights Reserved
#------------------------------------------------------------

#!/usr/bin/perl -w

###### ----------------   BA_Files_Name_Compare.pl ------------------------- ############################
# this file porpuses:
#
# 1. check if there are two files with the same name.
#    if there are it will print there location and will stop compilation
# 2. manufacture a file 'FilesEntities.txt' with all the doj files pathes
#    this file will be used int eh Sort_Copy_files.pl file
#
###### -------------------------------------------------- ############################

#defines a hash for user switches
%dTable=(-h=>\&help,
		 -i=>\&Input,
		 -p=>\&TargetDirPathFunc);

# function : help function for user
# ---------------------------------
sub help
{
	print "--------------------------------------------------------------------------------";
	print "this file is part of the BA module.\n";
	print "this file porpuse is to check if there are two files with the same name.\n";
	print "the program receive the project root directory from macro.mk in the target\n";
	print "Input:  Program must receive as an input the Text File library name \n"; 
	print "Usage:  BA_Frozen_Label_Mapping [-h -i]  <Text File Libaray Name> -p <Target Path>\n"; 
}
# function : get input library
# -------------------------------
sub Input
{
	if(!defined($FileLibrary = shift @ARGV))
	{
		print "ERROR: missing File library Input\n";
		exit 1;
	}
}

sub TargetDirPathFunc
{
	if(!defined($TargetDirPath = shift @ARGV))
	{
		print "ERROR: missing output path after -p\n";
		exit 1;
	}
}

# get program arguments
# -------------------------------------
while ($p=shift @ARGV)
{
	if (exists $dTable{$p})
	{
		$dTable{$p}->();
	}
	else
	{
		print "Illigal Switch $p\n";
		help();
		exit;
	}
}

##########  get defines from macro.mk  #################

$MacroPath = "..\\build\\macros.mk";
open (MACRO,$MacroPath) || die "cant open macros.mk\n" ;
$templine = <MACRO>;
while(defined($templine))
{
		if ($templine=~/BUILD_TYPE=(.*)/)
		{
			$TargetVariant = $1;
		}
		if ($templine=~/CBA_ROOT=(.*)/)
		{
			$RootDirectory = $1;
		}
		if ($templine=~/HW_PLATFORM_VARIANT=(.*)/)
		{
			#$PlatformVariant = $1;
		}
		if ($templine=~/BUILD_SCENARIO=(.*)/)
		{
			$BuildScenario = $1;
		}
		if ($templine=~/TARGET_VARIANT=(.*)/)
		{
			$ObjDirectory = $1;
			#$PlatformVariant = $1;
		}

		# READ NEXT LINE
		$templine = <MACRO>;
}
close(MACRO);

#in case of no automation
if (( $TargetVariant !~ /BUILD_FROZEN_FILES/ ) && ( $TargetVariant !~ /BUILD_TARGET_FILES/ ))
{
	exit;
}

# Project paths
$BuildDirPath = "$TargetDirPath"."\\"."build";
$OutPutFilesPath = "$BuildDirPath"."\\"."$FileLibrary";

#open the files name list file - generated by the gnumake command
$NamesPath = "$BuildDirPath"."\\"."Files_Names_list.txt";
open(LOG, $NamesPath) || die "can't open : Files_Names_list.txt - problem with gnumake";
$templine = <LOG>;
$error=0;
$type = -1;
print "--------- COMPARING PROJECT FILES NAMES PERL SCRIPT ---------\n";
print "start compare names...\n";
while(defined($templine))
{
	# we extract the files entity for knowing where are the files if there are two with the same name
	# and, later on create the path for the doj file
	if ($templine =~ (/Package build files \[(.*)\]/))
	{
		$entity_name = $1;#hold part of the path to the doj file
		$type = 0;
	}
	if ($templine =~ (/Group local build files \[(.*)\]/))
	{
		$entity_name = $1;#hold part of the path to the doj file
		$type = 1;
	}
	if ($templine =~ (/Target local build files \[(.*)\]/))
	{
		$entity_name = $1;#hold part of the path to the doj file
		$Curlibrary = "$TargetDirPath"."\\"."obj_$ObjDirectory";
	}
	if ($templine=~ /Source.*: (.*)$/) #in this line there are all the source files in the package/group
	{
		@a=split(qq( ),$1);
		# here we split to group and package - note that for each entety (group or package) the regular expretions are different
		# beacuse of the pattern of the output of the gnumake 'files' command
		if ( $type==0 )
		# this type is package :
		# we read another line to get the library line
		# with the entity name we concat the final directory to the path
		{
			$templine = <LOG>;
			@library = split(qq( ),$templine);
			@entity_name = split (/\\/,$entity_name);
			if ( defined ($entity_name[1]))
			{
				$library[2] =~ s/(.*)\\.*/$1/;
				$entity_name1 ="\\obj_".$entity_name[0]."_".$entity_name[1];
				$library[2] = $library[2].$entity_name1;
			}
			else
			{
				$library[2] =~ s/(.*)\\.*/$1/;
				$entity_name1 ="\\obj_".$entity_name[0];
				$library[2] = $library[2].$entity_name1;

			}
			if (defined($library[2]))
			{
				$Curlibrary = $library[2];
			}
		}
		if ( $type==1 )
		# this type is Group :
		# we read three tine the next line to get the library line
		# with the entity name we concat the final directory to the path
		{
			$templine = <LOG>;
			$templine = <LOG>;
			$templine = <LOG>;
			@library = split(qq( ),$templine);
			@entity_name =split (/\\/,$entity_name);
			if ( defined ($entity_name[1]))
			{
				$library[2] =~ s/(.*)\\.*/$1/;
				$entity_name1 ="\\obj_".$entity_name[0]."_".$entity_name[1];
				$library[2] = $library[2].$entity_name1;
			}
			else
			{
				$library[2] =~ s/(.*)\\.*/$1/;
				$entity_name1 ="\\obj_".$entity_name[0];
				$library[2] = $library[2].$entity_name1;
			}
			if (defined($library[2]))
			{
				$Curlibrary = $library[2];
			}
		}
		# here we check if there are any two files with the same name
		# we also create a hash with the files pathes
		foreach $a (@a)
		{
			$a =~ s/^(\w+)\.\w+$/$1/;
			$a =~ tr/[A-Z]/[a-z]/;
			if (not defined $a{$a})
			{
		   		$a{$a}=$entity_name;
			}
			else
			{
		   		print qq(ERROR : $a found in $a{$a} and $entity_name\n);
		   		$error += 1;
			}
			$library{$a} = $Curlibrary;
		}
	}
	$templine = <LOG>;

}

close(LOG);
#printing all the files with their entities
$EntitiesPath = ">".$OutPutFilesPath."\\"."FilesEntities_".$BuildScenario.".txt";
open(LIBRARY,$EntitiesPath)||die "Cant open FilesEntities.txt\n" ;
foreach $CurrentFileName (keys (%a))
{
	print LIBRARY "$CurrentFileName ";
	print LIBRARY "$library{$CurrentFileName}\n";
}
close(LIBRARY);


# we send error to the batch file - it should stop the procedure of the Build
exit 1 if ($error!=0);
print "finished comparing the names\n";
