#------------------------------------------------------------
# (C) Copyright [2006-2008] Marvell International Ltd.
# All Rights Reserved
#------------------------------------------------------------

use File::Basename;

$this_script = $0;

( ( scalar @ARGV ) < 1 )
  && die
"Usage: $0 <C header file>.h \nOutput Will be written into <C header file>_.h";
##$input_file = shift(@ARGV);

my $common_path = shift @ARGV;

foreach my $input_file (@ARGV)
  {
    ProcessFile("$common_path\\$input_file");
  }

exit 0;

#---------------------- END OF MAIN ----------------------

sub ProcessFile
  {

    my $c_file = shift(@_);

    local *CFILE;
    local *INCFILE;

    open( CFILE, "< $c_file" ) or die "Can't open input file '$c_file'.\n";
    my ( $in_name, $in_path, $in_suf ) = fileparse( $c_file, '\.\w+' );
    my $inc_file = $in_path . $in_name . "_" . $in_suf;

    $orig_file_time   = -M $c_file;
    $parsed_file_time = -M $inc_file;
    if ( ($parsed_file_time) && ( $parsed_file_time < $orig_file_time ) )
      {

# header_.h already exists, and it's time stamp is newer than that of the original header.h
# in this case we dont want to recreate the header_.h file, so we just quit
        return;
      }

    print "converting " . basename($c_file) . "\n";

    open( INCFILE, "> $inc_file" )
      or die "Can't open output file '$inc_file'.\n";

    print INCFILE
"//\n// This file was automatically generated by $0 from $c_file file.\n//\n";

    #print INCFILE "; Creation_date:" .  . "\n;\n";

    my $cline;
    while ( $cline = <CFILE> )
      {

        #  print "-->$cline<---";
        $cline =~ s/(\W\d+)L/$1/g;  # remove L from the end of decimal constants
        $cline =~ s/(\W0x[a-fA-F0-9]+)L/$1/g
          ;    # remove L from the end of hexadecimal constants
        if ( $cline =~ /^\s*\/\*.*$/ )
          {
            if ( $cline =~ /^.*\*\/\s*$/ ) { print INCFILE "$cline"; }
            else
              {
                print INCFILE "$cline";
                my $flag = 1;
                while ( ( $flag == 1 ) && ( $cline = <CFILE> ) )
                  {
                    if ( $cline =~ /^.*\*\/\s*$/ )
                      {
                        print INCFILE "$cline";
                        $flag = 0;
                      }
                    else { print INCFILE "$cline"; }
                  }    # while
              }    # else
          }    #if
        elsif ( $cline =~ /^\s*\/\// ) { print INCFILE "$cline"; }
        elsif ( $cline =~ /^\s*\#define\s+/ )
          {    # replace define
            print INCFILE "$cline";
            if ( $cline =~ /\\\s*$/ )
              {
                while (( $cline = <CFILE> )
                    && ( $cline =~ /\\\s*$/ ) )
                  {
                    print INCFILE "$cline";
                  }
                print INCFILE "$cline";
              }
            next;
          }    # if define
        elsif ( $cline =~ /\benum\b/ )
          {    # replace enum sequence
            my $comments  = "";
            my $lastvalue = "0";
            my $incvalue  = 0;
            print INCFILE "// $cline";

            while ( ( $cline = <CFILE> ) && !( $cline =~ /}/ ) )
              {

                if ( $cline =~ /^\s+$/ ) { print INCFILE "\n"; next; }
                $cline =~ s/\{//;

                # If there is /* */ style comments
                if ( $cline =~ /^\s*\/\*.*$/ )
                  {
                    if ( $cline =~ /^.*\*\/\s*$/ )
                      {
                        print INCFILE "// $cline";
                      }
                    else
                      {
                        print INCFILE "// $cline";
                        my $flag = 1;
                        while ( ( $flag == 1 ) && ( $cline = <CFILE> ) )
                          {
                            if ( $cline =~ /^.*\*\/\s*$/ )
                              {
                                print INCFILE "// $cline";
                                $flag = 0;
                              }
                            else { print INCFILE "// $cline"; }
                          }    # while
                      }    # else
                    next;
                  }    #if

                #			$cline =~ s/\/\*/\/\/ \/\*/;
                $comments = "";
                if ( $cline =~ m/\/\/(.*)$/ ) { $comments = $1; }
                $cline =~ s/\/\/.*//;
                $cline =~ s/=/ /;
                $cline =~ s/,//;
                $cline =~ s/%^\s*/%^/;
                $cline =~ s/\s+/ /g;

                my @cline_list = split( ' ', $cline );
                if ( scalar @cline_list == 1 )
                  {
                    print INCFILE
                      "#define\t$cline_list[0]\t( $lastvalue + $incvalue";
                    $incvalue++;
                    print INCFILE " )\t// $comments \n";
                  }
                elsif ( scalar @cline_list > 1 )
                  {
                    $incvalue  = 1;
                    $lastvalue = $cline_list[0];
                    print INCFILE "#define\t$cline_list[0]\t( ";
                    my $i = 0;
                    foreach $memlist (@cline_list)
                      {
                        if ( $i != 0 ) { print INCFILE "$memlist "; }
                        $i++;
                      }    # foreach
                    print INCFILE " )\t// $comments\n";
                  }    # elseif
                else
                  {
                    if ( $comments =~ /\w+/ )
                      {
                        print INCFILE "\t// $comments\n";
                      }
                    else { print INCFILE "\n"; }
                  }    # else
              }    # while

          }    #elsif
        elsif ( $cline =~ /^\s*\#include\s+[\"\<](.+)[\"\>](.*)/ )
          {
            my $inName     = $1;
            my $longName   = "";
            my $restOfLine = $2;

            $longName = $in_path . $inName;

            if ( -e $longName )
              {
                my ( $out_name, $out_path, $out_suf ) =
                  fileparse( $inName, '\.\w+' );
                my $longTime = -M $longName;
                my $outTime  = $longTime;
                my $outName;
                my $suffix;

                if ( !( $inName =~ /_\./ ) ) { $suffix = "_"; }

                $outName =
                  $in_path . $out_path . $out_name . $suffix . $out_suf;

                if ( -e $outName ) { $outTime = -M $outName; }

         #print "perl $this_script $longName [$longTime] $outName [$outTime]\n";
                if ( ( $outTime >= 0 ) && ( $longTime <= $outTime ) )
                  {
                    if ( !( $inName =~ /_\./ ) )
                      {

                        #print "perl $this_script $longName \n";
                        ProcessFile($longName);
                      }
                  }
                else { ParseIncludeFile($longName); }

                # ---- Changed By Kiril
                # include "file name" only
                #
                # WAS : print INCFILE "#include \"$outName" ."\"$restOfLine \n";
                print INCFILE "#include \"$out_name"
                  . "$suffix"
                  . "$out_suf"
                  . "\"$restOfLine \n";
              }
            else
              {
                my ( $out_name, $out_path, $out_suf ) =
                  fileparse( $inName, '\.\w+' );
                my $outname;

                if ( !( $inName =~ /_\./ ) )
                  {
                    $outName = $out_name . "_" . $out_suf;
                  }
                else
                  {
                    $outName = $out_name . $out_suf;
                  }
                print INCFILE "#include \"$outName"
                  . "\"$restOfLine \n";    #print INCFILE $cline;
              }
          }
        elsif (( $cline =~ /^\s*$/ )
            || ( $cline =~ /^\s*\#/ ) )
          {

            #if ( $cline =~ /^\s+$/ ) { print INCFILE "\n"; }
            #else {	print INCFILE "// $cline"; }
            print INCFILE "$cline";
          }
        else
          {

            #if ( $cline =~ /^\s+$/ ) { print INCFILE "\n"; }
            #else {	print INCFILE "// $cline"; }
            print INCFILE "// $cline";
          }
      }    # while FILE

  }    # sub ProcessFile

sub ParseIncludeFile
  {

#    my $fileName = shift(@_);
#    my ( $in_name, $in_path, $in_suf ) = fileparse( $fileName, '\.\w+' );

    #print "parsing $fileName \n";
#    local *INFILE;
#    open( INFILE, "< $fileName" )
#      or die " ParseIncludeFile: Can't open input file '$fileName'.\n";

#    my $cline;

#    while ( $cline = <INFILE> )
#      {
#        if ( $cline =~ /^\s*\#include\s+[\"\<](.+)[\"\>].*/ )
#          {
#            my $inName = $in_path . $1;
#            if ( -e $inName )
#              {

                #print "\t $inName \n";
#                my ( $out_name, $out_path, $out_suf ) =
#                  fileparse( $inName, '\.\w+' );
#                my $outName;
#                my $suffix;

#                if ( !( $inName =~ /_\./ ) ) { $suffix = "_"; }
#                $outName = $out_path . $out_name . $suffix . $out_suf;

#                my $inTime  = -M $inName;
#                my $outTime = $inTime;
#                if ( -e $outName ) { $outTime = -M $outName; }

                #print "$inName [$inTime] $outName [$outTime]\n";
#                if ( ( $outTime >= 0 ) && ( $inTime <= $outTime ) )
#                  {
#                    if ( !( $inName =~ /_\./ ) )
#                      {

                        #print "perl $this_script $inName \n";
#                        ProcessFile($inName);
#                      }
#                  }
#                else { ParseIncludeFile($inName); }
#              }
#          }

#      }

#    close INFILE;
  }
