#------------------------------------------------------------
# (C) Copyright [2006-2008] Marvell International Ltd.
# All Rights Reserved
#------------------------------------------------------------

#* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
#* DSPC Proprietary Information, (C) COPYRIGHT 2000 DSPC, an Intel Company
#* File name:    comap.pl
#* Programmer:   Evgeny M.
#* Create Date:  May, 2002                                                   
#* Description:                                                              
#*  This utility builds information table about all comapped sections
#* 
#* Notes:
#*  
#* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

#configuration parameters and default values
$DEBUG = 0;
$Verbose = 0;
$ComapSymbol = "COMAP";
$ComapDataSegmentName = "GSDATA_PATCH_INFO";
$RunAddrSymbol = "_runaddr";
$LoadAddrSymbol = "_loadaddr";
$SizeSymbol = "_size";

$Usage =          "Usage: $0 <Pre-processed ldf file> <C-header file with \"comapped\" information> [-s <ComapDataSegmentName>] [-v]\n";
$Usage = $Usage . " Generates FTK file, formatted in special way for the Boot Loader program.\n";
$Usage = $Usage . " Options:\n";
$Usage = $Usage . "  -s <ComapDataSegmentName>    specifies segment name of generated data.\n\n";
$Usage = $Usage . "  -v                           do it verbosely - print list of input and output sections.\n\n";

((scalar @ARGV) < 2) && die "$Usage";

$ThisScriptName = $0;
$in_name = shift (@ARGV);
$out_name = shift (@ARGV);

#process parameters and options
$ParamNum = (scalar @ARGV);
while ( $ParamNum != 0 ) { 
  $param2 = shift (@ARGV);
  if ( $param2 =~ /^-.*/ ) {
	if    ( $param2 =~ /^-v$/ ) { $Verbose = 1; }
	if    ( $param2 =~ /^-s$/ ) { $ComapDataSegmentName = shift (@ARGV); }
	else {die "$0: '$param2' - unknown option\n";}
  }
  else {die "$0: '$param2' - unknown option\n";}

  $ParamNum = scalar(@ARGV);
}

open(INFILE , "< $in_name") || die "$0: Can't open '$in_name' file.\n";
open(OUTFILE , "> $out_name") || die "$0: Can't open '$out_name' file.\n";

$SectionDB = ();

# Read the input file
while ( $line = <INFILE> ) {

  $Section = {};

  if ( $line =~ /^\s*$ComapSymbol/ ) { 
	# start COMAP
	#while ( !( $line =~ /\>\s*[\w,\d]+\s+[\w,\d]+\s*$/) ) {
	#  $line .= <INFILE>;
	#} 
	while ( !( $line =~ /$ComapSymbol\s+[\w,\d]+\s*/ ) ) {
	  $line .= <INFILE>;
	} 
	$line =~ m/$ComapSymbol\s+([\w,\d]+)\s*/;
	$Section->{RunAddr}  = $1 . $RunAddrSymbol;
	$Section->{LoadAddr} = $1 . $LoadAddrSymbol;
	$Section->{Size}     = $1 . $SizeSymbol;
	
	push @SectionDB, $Section;
  }
} # while ( $line = <INFILE> )

if ( ($DEBUG == 1) || ($Verbose == 1) ) {
  print "Comapped sections **********************************************************\n";
  for $el ( @SectionDB ) {
	printf "RunAddr = %s   LoadAddr = %s   Size = %s\n", $el->{RunAddr}, $el->{LoadAddr}, $el->{Size};
  }
}

$NumSections = scalar ( @SectionDB );

print OUTFILE "// this file was automatically generated by $ThisScriptName \n\n";
print OUTFILE "#define GSDATA_PATCHES_NUM   $NumSections \n";
if ( $NumSections != 0 ) {

  for $el ( @SectionDB ) {
	printf OUTFILE "extern char %s[], %s[], %s[];\n", $el->{LoadAddr}, $el->{RunAddr}, $el->{Size};
  }

  print OUTFILE " segment( \"" . $ComapDataSegmentName . "\" )\n";
  print OUTFILE "PatchInfoT PatchInfoDB[ GSDATA_PATCHES_NUM ] = {\n";
  for $el ( @SectionDB ) {
	printf OUTFILE "\t{ (unsigned char *)&%s, (unsigned char *)&%s, (unsigned long)&%s }", $el->{LoadAddr}, $el->{RunAddr}, $el->{Size};
	if ( $i != $NumSections ) { printf OUTFILE ",\n"; }
	else { printf OUTFILE "\n"; }
  }
  print OUTFILE "};\n\n";
}

print OUTFILE " segment( \"" . $ComapDataSegmentName . "\" )\n";
print OUTFILE "unsigned long ComappedSectionsNum = GSDATA_PATCHES_NUM;\n";


close INFILE;
close OUTFILE;
exit 0;
