#include "mbtk_gpio.h"


unsigned short mbtk_get_function_pin_gpio(mbtk_project_function_pin_enum pin_name)
{
	const unsigned short PROJECT_PIN_DEFINED[MBTK_MAX_GPIO_FUNC_PIN]=  //please define the order as mbtk_project_function_pin_enum
	{
#if defined(MBTK_PRODUCT_BSP_L511_6)
#if  defined(MBTK_PRODUCT_L511C_6D) || defined(MBTK_PRODUCT_L511CS_6D) || defined(MBTK_PRODUCT_L511AS_6D)
			 mbtk_gpio_70,////MBTK_STATUS_PIN = 0,
			 mbtk_gpio_6,////MBTK_NET_STATUS_LED_PIN,
			 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_NET_MODE_LED_PIN,
			 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_WAKEUP_IN_PIN,
			 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_AP_READY_PIN,
			 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_FLIGTH_MODE_PIN,
			 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_WAKEOUT_PIN,
			 mbtk_gpio_69,////MBTK_USIM_DET,
			 mbtk_gpio_51,///MBTK_CP_UART_RXD,
			 mbtk_gpio_52,///MBTK_CP_UART_TXD,
			 mbtk_gpio_53,///MBTK_CP_UART_CTS,
			 mbtk_gpio_54,///MBTK_CP_UART_RTS,
			 mbtk_gpio_27,///MBTK_CP_UART_DTR,
			 mbtk_gpio_31,///MBTK_CP_UART_RI,
			 mbtk_gpio_124,////MBTK_CP_UART_DCD,
			 mbtk_gpio_30,///MBTK_AP_UART1_TXD,
			 mbtk_gpio_29,///MBTK_AP_UART1_RXD,
			 mbtk_gpio_35,///MBTK_GPS_RXD_PIN,
			 mbtk_gpio_36,///MBTK_GPS_TXD_PIN,
			 mbtk_gpio_13,///MBTK_I2C_SDA_PIN,
			 mbtk_gpio_12,///MBTK_I2C_SCL_PIN,
			 mbtk_gpio_7,//MBTK_LCD_TE_PIN,
			 mbtk_gpio_34,///MBTK_LCD_CS_PIN,
			 mbtk_gpio_35,///MBTK_LCD_SPI_RS,
			 mbtk_gpio_32,//MBTK_LCD_SPI_RST,
			 mbtk_gpio_36,///MBTK_LCD_SPI_DOUT,
			 mbtk_gpio_33,///MBTK_LCD_SPI_CLK,
			 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
			 mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
			 mbtk_gpio_26,///MBTK_CAM_I2C_SDA,
			 mbtk_gpio_21,///MBTK_CAM_SPI_MCLK,
			 mbtk_gpio_22,///MBTK_CAM_SPI_CLK,
			 mbtk_gpio_24,///MBTK_CAM_SPI_DATA0,
			 mbtk_gpio_23,///MBTK_CAM_SPI_DATA1,
			 mbtk_gpio_20,///MBTK_CAM_PWDN1,
			 mbtk_ldo_7,//M//MBTK_CAM_VDD,
			 mbtk_gpio_17,///MBTK_PCM_SYNC,
			 mbtk_gpio_19,///MBTK_PCM_RXD,
			 mbtk_gpio_18,///MBTK_PCM_TXD,
			 mbtk_gpio_16,///MBTK_PCM_CLK,
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_UART_RXD,
			 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_GPS_UART_TXD,
			 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_GPS_RST,
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_SLEEP_EN,
			 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_HOST_WAKE_GPS,N
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_WAKE_HOST,
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_32K,
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_BLINK,
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
			 mbtk_gpio_17,///MBTK_AUDIO_PA_EN,
			 MBTK_FUNCTION_PIN_NOT_USED, //MBTk_SPI_CLK,
			 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_SPI_DOUT,
			 MBTK_FUNCTION_PIN_NOT_USED,//	MBTK_SPI_DIN,
			 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_SPI_CS,
			 MBTK_FUNCTION_PIN_NOT_USED,//	 MBTK_GPIO_PIN_1,
			 MBTK_FUNCTION_PIN_NOT_USED,//	 MBTK_GPIO_PIN_2,
#else
     mbtk_gpio_0,////MBTK_STATUS_PIN = 0,
	 mbtk_gpio_6,////MBTK_NET_STATUS_LED_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_NET_MODE_LED_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_WAKEUP_IN_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_AP_READY_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_FLIGTH_MODE_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,////MBTK_WAKEOUT_PIN,
	 mbtk_gpio_7,////MBTK_USIM_DET,
	 mbtk_gpio_51,///MBTK_CP_UART_RXD,
	 mbtk_gpio_52,///MBTK_CP_UART_TXD,
	 mbtk_gpio_53,///MBTK_CP_UART_CTS,
	 mbtk_gpio_54,///MBTK_CP_UART_RTS,
	 mbtk_gpio_27,///MBTK_CP_UART_DTR,
	 mbtk_gpio_31,///MBTK_CP_UART_RI,
	 mbtk_gpio_32,////MBTK_CP_UART_DCD,
	 mbtk_gpio_30,///MBTK_AP_UART1_TXD,
	 mbtk_gpio_29,///MBTK_AP_UART1_RXD,
	 mbtk_gpio_35,///MBTK_GPS_RXD_PIN,
	 mbtk_gpio_36,///MBTK_GPS_TXD_PIN,
	 mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
	 mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_TE_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_CS_PIN,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_RS,
	 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_SPI_RST,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_DOUT,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_CLK,
	 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_I2C_SCL,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_I2C_SDA,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_MCLK,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_CLK,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA0,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA1,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_PWDN1,
	 MBTK_FUNCTION_PIN_NOT_USED,//M//MBTK_CAM_VDD,
	 mbtk_gpio_17,///MBTK_PCM_SYNC,
	 mbtk_gpio_19,///MBTK_PCM_RXD,
	 mbtk_gpio_18,///MBTK_PCM_TXD,
	 mbtk_gpio_16,///MBTK_PCM_CLK,
	 mbtk_gpio_35,///MBTK_GPS_UART_RXD,
	 mbtk_gpio_36,//MBTK_GPS_UART_TXD,
	 mbtk_gpio_37,//MBTK_GPS_RST,
	 mbtk_gpio_123,///MBTK_GPS_SLEEP_EN,
	 mbtk_gpio_33,//MBTK_HOST_WAKE_GPS,N
	 mbtk_gpio_34,///MBTK_GPS_WAKE_HOST,
	 mbtk_gpio_122,///MBTK_GPS_32K,
	 mbtk_gpio_28,///MBTK_GPS_BLINK,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
	 mbtk_gpio_17,///MBTK_AUDIO_PA_EN,
	 MBTK_FUNCTION_PIN_NOT_USED, //MBTk_SPI_CLK,
	 MBTK_FUNCTION_PIN_NOT_USED,///MBTK_SPI_DOUT,
	 MBTK_FUNCTION_PIN_NOT_USED,//	MBTK_SPI_DIN,
	 MBTK_FUNCTION_PIN_NOT_USED,//MBTK_SPI_CS,
	 MBTK_FUNCTION_PIN_NOT_USED,//	 MBTK_GPIO_PIN_1,
	 MBTK_FUNCTION_PIN_NOT_USED,//	 MBTK_GPIO_PIN_2,
	#endif
#endif
	 #if defined(MBTK_PRODUCT_L501GN_3S)||defined(MBTK_PRODUCT_L501G_3S)||defined(MBTK_PRODUCT_L501C_3S)
	    mbtk_gpio_8,////MBTK_STATUS_PIN = 0,
	    mbtk_gpio_4,////MBTK_NET_STATUS_LED_PIN,
	    MBTK_FUNCTION_PIN_NOT_USED ,////MBTK_NET_MODE_LED_PIN,
	    mbtk_gpio_34,////MBTK_WAKEUP_IN_PIN,
	    MBTK_FUNCTION_PIN_NOT_USED,////MBTK_AP_READY_PIN,
		mbtk_gpio_5,////MBTK_FLIGTH_MODE_PIN,
	    mbtk_gpio_80,////MBTK_WAKEOUT_PIN,
	    mbtk_gpio_3,////MBTK_USIM_DET,
		mbtk_gpio_51,///MBTK_CP_UART_RXD,
		mbtk_gpio_52,///MBTK_CP_UART_TXD,
		mbtk_gpio_53,///MBTK_CP_UART_CTS,
		mbtk_gpio_54,///MBTK_CP_UART_RTS,
		mbtk_gpio_27,///MBTK_CP_UART_DTR,
		mbtk_gpio_31,///MBTK_CP_UART_RI,
	    mbtk_gpio_32,////MBTK_CP_UART_DCD,
		mbtk_gpio_30,///MBTK_AP_UART1_TXD,
		mbtk_gpio_29,///MBTK_AP_UART1_RXD,
	   	mbtk_gpio_0,///MBTK_GPS_RXD_PIN,
		mbtk_gpio_1,///MBTK_GPS_TXD_PIN,
		mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
		mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_TE_PIN,
	   	MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_CS_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_RS,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_SPI_RST,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_DOUT,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
		mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
		mbtk_gpio_26,///MBTK_CAM_I2C_SDA,	
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_MCLK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA0,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA1,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_PWDN1,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_VDD,
		mbtk_gpio_17,///MBTK_PCM_SYNC,
		mbtk_gpio_19,///MBTK_PCM_RXD,
		mbtk_gpio_18,///MBTK_PCM_TXD,
		mbtk_gpio_16,///MBTK_PCM_CLK,
	   	mbtk_gpio_0,///MBTK_GPS_UART_RXD,
		mbtk_gpio_1,///MBTK_GPS_UART_RXD,
		mbtk_gpio_21,//MBTK_GPS_RST,
		mbtk_gpio_123,///MBTK_GPS_SLEEP_EN,
		mbtk_gpio_33,//MBTK_HOST_WAKE_GPS,N
		mbtk_gpio_35,///MBTK_GPS_WAKE_HOST,
		mbtk_gpio_122,///MBTK_GPS_32K,
		mbtk_gpio_2,///MBTK_GPS_BLINK
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
#if defined(MBTK_PRODUCT_L503_6C_MINI_PCIE)	
       mbtk_gpio_4,  //MBTK_AUDIO_PA_EN , not used for AP ready
#else
		mbtk_gpio_78,///MBTK_AUDIO_PA_EN,
#endif		
		mbtk_gpio_12, //MBTk_SPI_CLK,
		mbtk_gpio_15,///MBTK_SPI_DOUT,
	    mbtk_gpio_14,//  MBTK_SPI_DIN,
        mbtk_gpio_13,//MBTK_SPI_CS,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_1,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_2,
#elif  defined(MBTK_PRODUCT_BSP_L510_3)
	    mbtk_gpio_6,////MBTK_STATUS_PIN = 0,
	    mbtk_gpio_4 ,////MBTK_NET_STATUS_LED_PIN,
	    MBTK_FUNCTION_PIN_NOT_USED,////MBTK_NET_MODE_LED_PIN,
	    mbtk_gpio_5,////MBTK_WAKEUP_IN_PIN,
	    MBTK_FUNCTION_PIN_NOT_USED,////MBTK_AP_READY_PIN,
		mbtk_gpio_24,////MBTK_FLIGTH_MODE_PIN,
	    mbtk_gpio_28,////MBTK_WAKEOUT_PIN,
	    mbtk_gpio_3,////MBTK_USIM_DET,
		mbtk_gpio_51,///MBTK_CP_UART_RXD,
		mbtk_gpio_52,///MBTK_CP_UART_TXD,
		mbtk_gpio_53,///MBTK_CP_UART_CTS,
		mbtk_gpio_54,///MBTK_CP_UART_RTS,
		mbtk_gpio_27,///MBTK_CP_UART_DTR,
		mbtk_gpio_31,///MBTK_CP_UART_RI,
	    mbtk_gpio_32,////MBTK_CP_UART_DCD,
		mbtk_gpio_30,///MBTK_AP_UART1_TXD,
		mbtk_gpio_29,///MBTK_AP_UART1_RXD,
	   	mbtk_gpio_0,///MBTK_GPS_RXD_PIN,
		mbtk_gpio_1,///MBTK_GPS_TXD_PIN,
		mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
		mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_TE_PIN,
	   	MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_CS_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_RS,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_SPI_RST,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_DOUT,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_I2C_SCL,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_I2C_SDA,	
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_MCLK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA0,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA1,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_PWDN1,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_VDD,
		mbtk_gpio_17,///MBTK_PCM_SYNC,
		mbtk_gpio_19,///MBTK_PCM_RXD,
		mbtk_gpio_18,///MBTK_PCM_TXD,
		mbtk_gpio_16,///MBTK_PCM_CLK,
	   	mbtk_gpio_0,///MBTK_GPS_UART_RXD,
		mbtk_gpio_1,///MBTK_GPS_UART_RXD,

#ifdef  defined(MBTK_PRODUCT_L510EN_3S)||defined(MBTK_PRODUCT_L510LAN_3S)
        mbtk_gpio_22,
#else
		mbtk_gpio_21,//MBTK_GPS_RST,
#endif
		mbtk_gpio_123,///MBTK_GPS_SLEEP_EN,
		mbtk_gpio_33,//MBTK_HOST_WAKE_GPS,N
		mbtk_gpio_34,///MBTK_GPS_WAKE_HOST,
#ifdef MBTK_PRODUCT_L510E_3S || MBTK_PRODUCT_L510LAN_3S
		mbtk_gpio_122,///MBTK_GPS_32K,
#else
		mbtk_gpio_124,///MBTK_GPS_32K,
#endif
		mbtk_gpio_2,///MBTK_GPS_BLINK
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
#ifdef MBTK_PRODUCT_L510LAN_3S
        mbtk_gpio_14,    ////MBTK_AUDIO_PA_EN,
#else
		mbtk_gpio_17,///MBTK_AUDIO_PA_EN,
#endif
        mbtk_gpio_12, //MBTk_SPI_CLK,
        mbtk_gpio_15,///MBTK_SPI_DOUT,
        mbtk_gpio_14,//  MBTK_SPI_DIN,
        mbtk_gpio_13,//MBTK_SPI_CS,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_1,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_2,

#elif  defined(MBTK_PRODUCT_L503_3S)
	    mbtk_gpio_8,////MBTK_STATUS_PIN = 0,
	    mbtk_gpio_9 ,////MBTK_NET_STATUS_LED_PIN,
	    mbtk_gpio_6,////MBTK_NET_MODE_LED_PIN,
	    mbtk_gpio_3,////MBTK_WAKEUP_IN_PIN,
	    mbtk_gpio_4,////MBTK_AP_READY_PIN,
		mbtk_gpio_5,////MBTK_FLIGTH_MODE_PIN,
	    mbtk_gpio_7,////MBTK_WAKEOUT_PIN,
	    mbtk_gpio_1,////MBTK_USIM_DET,
		mbtk_gpio_51,///MBTK_CP_UART_RXD,
		mbtk_gpio_52,///MBTK_CP_UART_TXD,
		mbtk_gpio_53,///MBTK_CP_UART_CTS,
		mbtk_gpio_54,///MBTK_CP_UART_RTS,
		mbtk_gpio_27,///MBTK_CP_UART_DTR,
		mbtk_gpio_28,///MBTK_CP_UART_RI,
	    mbtk_gpio_2,////MBTK_CP_UART_DCD,
		mbtk_gpio_30,///MBTK_AP_UART1_TXD,
		mbtk_gpio_29,///MBTK_AP_UART1_RXD,
	   	MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_RXD_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_TXD_PIN,
		mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
		mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
		mbtk_gpio_49,//MBTK_LCD_TE_PIN,
	   	mbtk_gpio_34,///MBTK_LCD_CS_PIN,
		mbtk_gpio_121,///MBTK_LCD_SPI_RS,
		mbtk_gpio_77,//MBTK_LCD_SPI_RST,
		mbtk_gpio_36,///MBTK_LCD_SPI_DOUT,
		mbtk_gpio_33,///MBTK_LCD_SPI_CLK,
		mbtk_gpio_49,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
		mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
		mbtk_gpio_26,///MBTK_CAM_I2C_SDA,	
		mbtk_gpio_21,///MBTK_CAM_SPI_MCLK,
		mbtk_gpio_22,///MBTK_CAM_SPI_CLK,
		mbtk_gpio_24,///MBTK_CAM_SPI_DATA0,
		mbtk_gpio_23,///MBTK_CAM_SPI_DATA1,
		mbtk_gpio_0,///MBTK_CAM_PWDN1,
		mbtk_ldo_7,///MBTK_CAM_VDD,
		mbtk_gpio_17,///MBTK_PCM_SYNC,
		mbtk_gpio_19,///MBTK_PCM_RXD,
		mbtk_gpio_18,///MBTK_PCM_TXD,
		mbtk_gpio_16,///MBTK_PCM_CLK,
	   	MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_UART_RXD,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_UART_RXD,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_GPS_RST,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_SLEEP_EN,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_HOST_WAKE_GPS,N
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_WAKE_HOST,
//#ifdef MBTK_PRODUCT_L510EN_3S
//		mbtk_gpio_122,///MBTK_GPS_32K,
//#else
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_32K,
//#endif
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_BLINK
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_AUDIO_PA_EN,
		mbtk_gpio_12, //MBTk_SPI_CLK,
		mbtk_gpio_15,///MBTK_SPI_DOUT,
	    mbtk_gpio_14,//  MBTK_SPI_DIN,
        mbtk_gpio_13,//MBTK_SPI_CS,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_1,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_2,
#elif  defined(MBTK_PRODUCT_L503E_3S)
        mbtk_gpio_8,////MBTK_STATUS_PIN = 0,
	    mbtk_gpio_9 ,////MBTK_NET_STATUS_LED_PIN,
	    mbtk_gpio_6,////MBTK_NET_MODE_LED_PIN,
	    mbtk_gpio_3,////MBTK_WAKEUP_IN_PIN,
	    mbtk_gpio_4,////MBTK_AP_READY_PIN,
		mbtk_gpio_5,////MBTK_FLIGTH_MODE_PIN,
	    mbtk_gpio_7,////MBTK_WAKEOUT_PIN,
	    mbtk_gpio_124,////MBTK_USIM_DET,
		mbtk_gpio_51,///MBTK_CP_UART_RXD,
		mbtk_gpio_52,///MBTK_CP_UART_TXD,
		mbtk_gpio_53,///MBTK_CP_UART_CTS,
		mbtk_gpio_54,///MBTK_CP_UART_RTS,
		mbtk_gpio_121,///MBTK_CP_UART_DTR,
		mbtk_gpio_122,///MBTK_CP_UART_RI,
	    mbtk_gpio_2,////MBTK_CP_UART_DCD,
		mbtk_gpio_30,///MBTK_AP_UART1_TXD,
		mbtk_gpio_29,///MBTK_AP_UART1_RXD,
	   	MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_RXD_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_TXD_PIN,
		mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
		mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
		mbtk_gpio_20,//MBTK_LCD_TE_PIN,
	   	mbtk_gpio_34,///MBTK_LCD_CS_PIN,
		mbtk_gpio_35,///MBTK_LCD_SPI_RS,
		mbtk_gpio_27,//MBTK_LCD_SPI_RST,
		mbtk_gpio_36,///MBTK_LCD_SPI_DOUT,
		mbtk_gpio_33,///MBTK_LCD_SPI_CLK,
		mbtk_gpio_49,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
		mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
		mbtk_gpio_26,///MBTK_CAM_I2C_SDA,	
		mbtk_gpio_21,///MBTK_CAM_SPI_MCLK,
		mbtk_gpio_22,///MBTK_CAM_SPI_CLK,
		mbtk_gpio_24,///MBTK_CAM_SPI_DATA0,
		mbtk_gpio_23,///MBTK_CAM_SPI_DATA1,
		mbtk_gpio_28,///MBTK_CAM_PWDN1,
		mbtk_ldo_7,///MBTK_CAM_VDD,
		mbtk_gpio_17,///MBTK_PCM_SYNC,
		mbtk_gpio_19,///MBTK_PCM_RXD,
		mbtk_gpio_18,///MBTK_PCM_TXD,
		mbtk_gpio_16,///MBTK_PCM_CLK,
	   	MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_UART_RXD,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_UART_RXD,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_GPS_RST,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_SLEEP_EN,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_HOST_WAKE_GPS,N
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_WAKE_HOST,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_32K,		
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_BLINK
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
		mbtk_gpio_17,///MBTK_AUDIO_PA_EN,
		mbtk_gpio_12, //MBTk_SPI_CLK,
		mbtk_gpio_15,///MBTK_SPI_DOUT,
	    mbtk_gpio_14,//  MBTK_SPI_DIN,
        mbtk_gpio_13,//MBTK_SPI_CS,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_1,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_2,
#elif  defined(MBTK_PRODUCT_L501E_3S) ||defined(MBTK_PRODUCT_L501E_3E) || defined(MBTK_PRODUCT_L501I_3E)
			mbtk_gpio_79 ,////MBTK_STATUS_PIN = 0,
			mbtk_gpio_8 ,////MBTK_NET_STATUS_LED_PIN,
			mbtk_gpio_4  ,//BTK_NET_MODE_LED_PIN,
			mbtk_gpio_34,///MBTK_WAKEUP_IN_PIN,
			MBTK_FUNCTION_PIN_NOT_USED,////MBTK_AP_READY_PIN,
			mbtk_gpio_5,////MBTK_FLIGTH_MODE_PIN,
			mbtk_gpio_80,///MBTK_WAKEOUT_PIN,
			MBTK_FUNCTION_PIN_NOT_USED,////MBTK_USIM_DET,
			mbtk_gpio_51,///MBTK_CP_UART_RXD,
			mbtk_gpio_52,///MBTK_CP_UART_TXD,
			mbtk_gpio_53,///MBTK_CP_UART_CTS,
			mbtk_gpio_54,///MBTK_CP_UART_RTS,
			mbtk_gpio_27,//MBTK_CP_UART_DTR,
			mbtk_gpio_31,//MBTK_CP_UART_RI,
			mbtk_gpio_32,///MBTK_CP_UART_DCD,
			mbtk_gpio_30,///MBTK_AP_UART1_TXD,
			mbtk_gpio_29,///MBTK_AP_UART1_RXD,
			mbtk_gpio_0,//MBTK_GPS_RXD_PIN,
			mbtk_gpio_1,///MBTK_GPS_TXD_PIN,
			mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
			mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
			MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_TE_PIN,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_CS_PIN,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_RS,
			MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_SPI_RST,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_DOUT,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_LCD_SPI_CLK,
			MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
			mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
			mbtk_gpio_26,///MBTK_CAM_I2C_SDA,	
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_MCLK,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_CLK,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA0,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA1,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_PWDN1,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_VDD,
			mbtk_gpio_17,///MBTK_PCM_SYNC,
			mbtk_gpio_19,///MBTK_PCM_RXD,
			mbtk_gpio_18,///MBTK_PCM_TXD,
			mbtk_gpio_16,///MBTK_PCM_CLK,
			mbtk_gpio_0,///MBTK_GPS_UART_RXD,
			mbtk_gpio_1,///MBTK_GPS_UART_RXD,
			mbtk_gpio_21,//MBTK_GPS_RST,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_SLEEP_EN,
			MBTK_FUNCTION_PIN_NOT_USED,//MBTK_HOST_WAKE_GPS,N
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_WAKE_HOST,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_32K,
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_BLINK
			MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
			mbtk_gpio_78,///MBTK_AUDIO_PA_EN,
			mbtk_gpio_12, //MBTk_SPI_CLK,
			mbtk_gpio_15,//BTK_SPI_DOUT,
			mbtk_gpio_14,//MBTK_SPI_DIN,
			mbtk_gpio_13,//MBTK_SPI_CS,
			MBTK_FUNCTION_PIN_NOT_USED,//	MBTK_GPIO_PIN_1,
			MBTK_FUNCTION_PIN_NOT_USED,//	MBTK_GPIO_PIN_2,
#elif  defined(MBTK_PRODUCT_L505C_6C)
			mbtk_gpio_0,////MBTK_STATUS_PIN = 0,
			mbtk_gpio_1,////MBTK_NET_STATUS_LED_PIN,
			mbtk_gpio_70,////MBTK_FLIGTH_MODE_PIN,
			mbtk_gpio_7,////MBTK_USIM_DET,
			mbtk_gpio_51,///MBTK_CP_UART_RXD,
			mbtk_gpio_52,///MBTK_CP_UART_TXD,
			mbtk_gpio_53,///MBTK_CP_UART_CTS,
			mbtk_gpio_54,///MBTK_CP_UART_RTS,
			mbtk_gpio_27,///MBTK_CP_UART_DTR,
			mbtk_gpio_31,///MBTK_CP_UART_RI,
			mbtk_gpio_69,////MBTK_CP_UART_DCD,
			mbtk_gpio_30,///MBTK_AP_UART1_TXD,
			mbtk_gpio_29,///MBTK_AP_UART1_RXD,
			mbtk_gpio_35,///MBTK_GPS_RXD_PIN,
			mbtk_gpio_36,///MBTK_GPS_TXD_PIN,
			mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
			mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
			mbtk_gpio_124,//MBTK_LCD_TE_PIN,
			mbtk_gpio_13,///MBTK_LCD_CS_PIN,
			mbtk_gpio_14,///MBTK_LCD_SPI_RS,
			mbtk_gpio_121,//MBTK_LCD_SPI_RST,
			mbtk_gpio_15,///MBTK_LCD_SPI_DOUT,
			mbtk_gpio_12,///MBTK_LCD_SPI_CLK,
			mbtk_gpio_6,//MBTK_PWM_PIN
			mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
			mbtk_gpio_26,///MBTK_CAM_I2C_SDA,
			mbtk_gpio_21,///MBTK_CAM_SPI_MCLK,
			mbtk_gpio_22,///MBTK_CAM_SPI_CLK,
			mbtk_gpio_24,///MBTK_CAM_SPI_DATA0,
			mbtk_gpio_23,///MBTK_CAM_SPI_DATA1,
			mbtk_gpio_20,///MBTK_CAM_PWDN1,
			mbtk_ldo_6,// MBTK_CAM_VDD,
			mbtk_gpio_17,///MBTK_AUDIO_PA_EN,
			mbtk_gpio_71, //MBTk_SPI_CLK,
			mbtk_gpio_74,///MBTK_SPI_DOUT,
			mbtk_gpio_73,//  MBTK_SPI_DIN,
			mbtk_gpio_72,//MBTK_SPI_CS,
			mbtk_gpio_3,//   MBTK_UART4_TX,
			mbtk_gpio_2,//   MBTK_UART4_RX,
#elif defined(MBTK_PRODUCT_BSP_L511_2)
	    MBTK_FUNCTION_PIN_NOT_USED,////MBTK_STATUS_PIN = 0,//zhengzhou for anfu rgb lcd+fstn lcd
		mbtk_gpio_69,////MBTK_NET_STATUS_LED_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,////MBTK_NET_MODE_LED_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,////MBTK_WAKEUP_IN_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,////MBTK_AP_READY_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,////MBTK_FLIGTH_MODE_PIN,
		MBTK_FUNCTION_PIN_NOT_USED,////MBTK_WAKEOUT_PIN,
		mbtk_gpio_84,////MBTK_USIM_DET,
		mbtk_gpio_51,///MBTK_CP_UART_RXD,
		mbtk_gpio_52,///MBTK_CP_UART_TXD,
		mbtk_gpio_53,///MBTK_CP_UART_CTS,
		mbtk_gpio_54,///MBTK_CP_UART_RTS,
		mbtk_gpio_74,///MBTK_CP_UART_DTR,
		mbtk_gpio_37,///MBTK_CP_UART_RI,
		mbtk_gpio_89,////MBTK_CP_UART_DCD,
		mbtk_gpio_72,///MBTK_AP_UART1_TXD,
		mbtk_gpio_71,///MBTK_AP_UART1_RXD,
		mbtk_gpio_2,///MBTK_GPS_RXD_PIN,
		mbtk_gpio_3,///MBTK_GPS_TXD_PIN,
		mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
		mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
		mbtk_gpio_86,//MBTK_LCD_TE_PIN,
		mbtk_gpio_34,///MBTK_LCD_CS_PIN,
		mbtk_gpio_35,///MBTK_LCD_SPI_RS,
		mbtk_gpio_55,//MBTK_LCD_SPI_RST,
		mbtk_gpio_36,///MBTK_LCD_SPI_DOUT,
		mbtk_gpio_33,///MBTK_LCD_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
		mbtk_gpio_49,///MBTK_CAM_I2C_SCL,
		mbtk_gpio_50,///MBTK_CAM_I2C_SDA,
		mbtk_gpio_68,///MBTK_CAM_SPI_MCLK,
		mbtk_gpio_4,///MBTK_CAM_SPI_CLK,
		mbtk_gpio_6,///MBTK_CAM_SPI_DATA0,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_CAM_SPI_DATA1,
		mbtk_gpio_5,///MBTK_CAM_PWDN1,
		MBTK_FUNCTION_PIN_NOT_USED,//M//MBTK_CAM_VDD,
		mbtk_gpio_13,///MBTK_PCM_SYNC,
		mbtk_gpio_14,///MBTK_PCM_RXD,
		mbtk_gpio_15,///MBTK_PCM_TXD,
		mbtk_gpio_12,///MBTK_PCM_CLK,
		mbtk_gpio_2,///MBTK_GPS_UART_RXD,
		mbtk_gpio_3,//MBTK_GPS_UART_TXD,
		mbtk_gpio_73,//MBTK_GPS_RST,
		mbtk_gpio_85,///MBTK_GPS_SLEEP_EN,
		mbtk_gpio_87,//MBTK_HOST_WAKE_GPS,N
		mbtk_gpio_88,///MBTK_GPS_WAKE_HOST,
		mbtk_gpio_56,///MBTK_GPS_32K,
		mbtk_gpio_57,///MBTK_GPS_BLINK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
		mbtk_gpio_13,///MBTK_AUDIO_PA_EN,
		MBTK_FUNCTION_PIN_NOT_USED, //MBTk_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_SPI_DOUT,
	    MBTK_FUNCTION_PIN_NOT_USED,//  MBTK_SPI_DIN,
        MBTK_FUNCTION_PIN_NOT_USED,//MBTK_SPI_CS,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_1,
        MBTK_FUNCTION_PIN_NOT_USED,//   MBTK_GPIO_PIN_2,
#else
	    mbtk_gpio_0,////MBTK_STATUS_PIN = 0,
		mbtk_gpio_9,////MBTK_NET_STATUS_LED_PIN,
		mbtk_gpio_6,////MBTK_NET_MODE_LED_PIN,
		mbtk_gpio_3,////MBTK_WAKEUP_IN_PIN,
		mbtk_gpio_4,////MBTK_AP_READY_PIN,
		mbtk_gpio_5,////MBTK_FLIGTH_MODE_PIN,
		mbtk_gpio_1,////MBTK_WAKEOUT_PIN,
		mbtk_gpio_7,////MBTK_USIM_DET,
		mbtk_gpio_51,///MBTK_CP_UART_RXD,
		mbtk_gpio_52,///MBTK_CP_UART_TXD,
		mbtk_gpio_53,///MBTK_CP_UART_CTS,
		mbtk_gpio_54,///MBTK_CP_UART_RTS,
		mbtk_gpio_27,///MBTK_CP_UART_DTR,
		mbtk_gpio_31,///MBTK_CP_UART_RI,
		mbtk_gpio_2,////MBTK_CP_UART_DCD,
		mbtk_gpio_30,///MBTK_AP_UART1_TXD,
		mbtk_gpio_29,///MBTK_AP_UART1_RXD,
		mbtk_gpio_35,///MBTK_GPS_RXD_PIN,
		mbtk_gpio_36,///MBTK_GPS_TXD_PIN,
		mbtk_gpio_11,///MBTK_I2C_SDA_PIN,
		mbtk_gpio_10,///MBTK_I2C_SCL_PIN,
		mbtk_gpio_124,//MBTK_LCD_TE_PIN,
		mbtk_gpio_13,///MBTK_LCD_CS_PIN,
		mbtk_gpio_14,///MBTK_LCD_SPI_RS,
		mbtk_gpio_121,//MBTK_LCD_SPI_RST,
		mbtk_gpio_15,///MBTK_LCD_SPI_DOUT,
		mbtk_gpio_12,///MBTK_LCD_SPI_CLK,
		MBTK_FUNCTION_PIN_NOT_USED,//MBTK_LCD_LCD_VDDIO,DDIO, connet to VDD1.8
		mbtk_gpio_25,///MBTK_CAM_I2C_SCL,
		mbtk_gpio_26,///MBTK_CAM_I2C_SDA,
		mbtk_gpio_21,///MBTK_CAM_SPI_MCLK,
		mbtk_gpio_22,///MBTK_CAM_SPI_CLK,
		mbtk_gpio_24,///MBTK_CAM_SPI_DATA0,
		mbtk_gpio_23,///MBTK_CAM_SPI_DATA1,
		mbtk_gpio_20,///MBTK_CAM_PWDN1,
		mbtk_ldo_6,//M//MBTK_CAM_VDD,
		mbtk_gpio_17,///MBTK_PCM_SYNC,
		mbtk_gpio_19,///MBTK_PCM_RXD,
		mbtk_gpio_18,///MBTK_PCM_TXD,
		mbtk_gpio_16,///MBTK_PCM_CLK,
		mbtk_gpio_35,///MBTK_GPS_UART_RXD,
		mbtk_gpio_36,//MBTK_GPS_UART_TXD,
		mbtk_gpio_37,//MBTK_GPS_RST,
		mbtk_gpio_123,///MBTK_GPS_SLEEP_EN,
		mbtk_gpio_33,//MBTK_HOST_WAKE_GPS,N
		mbtk_gpio_34,///MBTK_GPS_WAKE_HOST,
		mbtk_gpio_122,///MBTK_GPS_32K,
		mbtk_gpio_28,///MBTK_GPS_BLINK,
		MBTK_FUNCTION_PIN_NOT_USED,///MBTK_GPS_LNA_EN,
#if defined(MBTK_PRODUCT_L503_6C_MINI_PCIE)	
        mbtk_gpio_4,  //MBTK_AUDIO_PA_EN , not used for AP ready
#else
		mbtk_gpio_17,///MBTK_AUDIO_PA_EN,
#endif		
		mbtk_gpio_71, //MBTk_SPI_CLK,
		mbtk_gpio_74,///MBTK_SPI_DOUT,
	    mbtk_gpio_73,//  MBTK_SPI_DIN,
        mbtk_gpio_72,//MBTK_SPI_CS,
        mbtk_gpio_69,//   MBTK_GPIO_PIN_1,
        mbtk_gpio_70,//   MBTK_GPIO_PIN_2,
		#endif
	};  				

	
	if(pin_name >=MBTK_ADC1_PIN &&MBTK_ADC3_PIN >= pin_name)
	{
	   return (mbtk_adc_1+(pin_name - MBTK_ADC1_PIN));
	}
	
	
    if(MBTK_MAX_GPIO_FUNC_PIN > pin_name)
		return PROJECT_PIN_DEFINED[pin_name];   //return GPIO num
	else
		return MBTK_FUNCTION_PIN_NOT_USED;

		
}
