//PPC Version : V2.1.9.30
//PPL Source File Name : \tavor\Arbel\obj_PMD2NONE\prepass_results\mbtk_zip_api.ppp
//PPL Source File Name : \\mbtk\\miniz\\src\\mbtk_zip_api.c
typedef signed int ptrdiff_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef long double max_align_t ;
typedef unsigned long mz_ulong ;
typedef void * ( *mz_alloc_func ) ( void *opaque , size_t items , size_t size ) ;
typedef void ( *mz_free_func ) ( void *opaque , void *address ) ;
typedef void * ( *mz_realloc_func ) ( void *opaque , void *address , size_t items , size_t size ) ;
typedef mz_stream *mz_streamp ;
typedef unsigned char Byte ;
typedef unsigned int uInt ;
typedef mz_ulong uLong ;
typedef Byte Bytef ;
typedef uInt uIntf ;
typedef char charf ;
typedef int intf ;
typedef void *voidpf ;
typedef uLong uLongf ;
typedef void *voidp ;
typedef void *const voidpc ;
typedef signed char int8_t ;
typedef signed short int int16_t ;
typedef signed int int32_t ;
typedef signed __int64 int64_t ;
typedef unsigned char uint8_t ;
typedef unsigned short int uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned __int64 uint64_t ;
typedef signed char int_least8_t ;
typedef signed short int int_least16_t ;
typedef signed int int_least32_t ;
typedef signed __int64 int_least64_t ;
typedef unsigned char uint_least8_t ;
typedef unsigned short int uint_least16_t ;
typedef unsigned int uint_least32_t ;
typedef unsigned __int64 uint_least64_t ;
typedef signed int int_fast8_t ;
typedef signed int int_fast16_t ;
typedef signed int int_fast32_t ;
typedef signed __int64 int_fast64_t ;
typedef unsigned int uint_fast8_t ;
typedef unsigned int uint_fast16_t ;
typedef unsigned int uint_fast32_t ;
typedef unsigned __int64 uint_fast64_t ;
typedef signed int intptr_t ;
typedef unsigned int uintptr_t ;
typedef signed long long intmax_t ;
typedef unsigned long long uintmax_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef int ( *__heapprt ) ( void * , char const * , ... ) ;
typedef unsigned int size_t ;
typedef unsigned char mz_uint8 ;
typedef signed short mz_int16 ;
typedef unsigned short mz_uint16 ;
typedef unsigned int mz_uint32 ;
typedef unsigned int mz_uint ;
typedef int32_t mz_int64 ;
typedef int32_t mz_uint64 ;
typedef int mz_bool ;
typedef unsigned int MZ_FILE ;
typedef mz_bool ( *tdefl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef int ( *tinfl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef mz_uint32 tinfl_bit_buf_t ;
typedef size_t ( *mz_file_read_func ) ( void *pOpaque , mz_uint64 file_ofs , void *pBuf , size_t n ) ;
typedef size_t ( *mz_file_write_func ) ( void *pOpaque , mz_uint64 file_ofs , const void *pBuf , size_t n ) ;
typedef mz_bool ( *mz_file_needs_keepalive ) ( void *pOpaque ) ;
//PPC Version : V2.1.9.30
//PPL Source File Name : \tavor\Arbel\obj_PMD2NONE\prepass_results\miniz.ppp
//PPL Source File Name : \\mbtk\\miniz\\src\\miniz.c
typedef signed int ptrdiff_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef long double max_align_t ;
typedef unsigned long mz_ulong ;
typedef void * ( *mz_alloc_func ) ( void *opaque , size_t items , size_t size ) ;
typedef void ( *mz_free_func ) ( void *opaque , void *address ) ;
typedef void * ( *mz_realloc_func ) ( void *opaque , void *address , size_t items , size_t size ) ;
typedef mz_stream *mz_streamp ;
typedef unsigned char Byte ;
typedef unsigned int uInt ;
typedef mz_ulong uLong ;
typedef Byte Bytef ;
typedef uInt uIntf ;
typedef char charf ;
typedef int intf ;
typedef void *voidpf ;
typedef uLong uLongf ;
typedef void *voidp ;
typedef void *const voidpc ;
typedef signed char int8_t ;
typedef signed short int int16_t ;
typedef signed int int32_t ;
typedef signed __int64 int64_t ;
typedef unsigned char uint8_t ;
typedef unsigned short int uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned __int64 uint64_t ;
typedef signed char int_least8_t ;
typedef signed short int int_least16_t ;
typedef signed int int_least32_t ;
typedef signed __int64 int_least64_t ;
typedef unsigned char uint_least8_t ;
typedef unsigned short int uint_least16_t ;
typedef unsigned int uint_least32_t ;
typedef unsigned __int64 uint_least64_t ;
typedef signed int int_fast8_t ;
typedef signed int int_fast16_t ;
typedef signed int int_fast32_t ;
typedef signed __int64 int_fast64_t ;
typedef unsigned int uint_fast8_t ;
typedef unsigned int uint_fast16_t ;
typedef unsigned int uint_fast32_t ;
typedef unsigned __int64 uint_fast64_t ;
typedef signed int intptr_t ;
typedef unsigned int uintptr_t ;
typedef signed long long intmax_t ;
typedef unsigned long long uintmax_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef int ( *__heapprt ) ( void * , char const * , ... ) ;
typedef unsigned int size_t ;
typedef unsigned char mz_uint8 ;
typedef signed short mz_int16 ;
typedef unsigned short mz_uint16 ;
typedef unsigned int mz_uint32 ;
typedef unsigned int mz_uint ;
typedef int32_t mz_int64 ;
typedef int32_t mz_uint64 ;
typedef int mz_bool ;
typedef unsigned int MZ_FILE ;
typedef mz_bool ( *tdefl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef int ( *tinfl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef mz_uint32 tinfl_bit_buf_t ;
typedef size_t ( *mz_file_read_func ) ( void *pOpaque , mz_uint64 file_ofs , void *pBuf , size_t n ) ;
typedef size_t ( *mz_file_write_func ) ( void *pOpaque , mz_uint64 file_ofs , const void *pBuf , size_t n ) ;
typedef mz_bool ( *mz_file_needs_keepalive ) ( void *pOpaque ) ;
typedef unsigned char mz_validate_uint16 [ sizeof ( mz_uint16 ) == 2 ? 1 : -1 ] ;
typedef unsigned char mz_validate_uint32 [ sizeof ( mz_uint32 ) == 4 ? 1 : -1 ] ;
typedef unsigned char mz_validate_uint64 [ sizeof ( mz_uint64 ) == 4 ? 1 : -1 ] ;
//PPC Version : V2.1.9.30
//PPL Source File Name : \tavor\Arbel\obj_PMD2NONE\prepass_results\miniz_tdef.ppp
//PPL Source File Name : \\mbtk\\miniz\\src\\miniz_tdef.c
typedef signed int ptrdiff_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef long double max_align_t ;
typedef unsigned long mz_ulong ;
typedef void * ( *mz_alloc_func ) ( void *opaque , size_t items , size_t size ) ;
typedef void ( *mz_free_func ) ( void *opaque , void *address ) ;
typedef void * ( *mz_realloc_func ) ( void *opaque , void *address , size_t items , size_t size ) ;
typedef mz_stream *mz_streamp ;
typedef unsigned char Byte ;
typedef unsigned int uInt ;
typedef mz_ulong uLong ;
typedef Byte Bytef ;
typedef uInt uIntf ;
typedef char charf ;
typedef int intf ;
typedef void *voidpf ;
typedef uLong uLongf ;
typedef void *voidp ;
typedef void *const voidpc ;
typedef signed char int8_t ;
typedef signed short int int16_t ;
typedef signed int int32_t ;
typedef signed __int64 int64_t ;
typedef unsigned char uint8_t ;
typedef unsigned short int uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned __int64 uint64_t ;
typedef signed char int_least8_t ;
typedef signed short int int_least16_t ;
typedef signed int int_least32_t ;
typedef signed __int64 int_least64_t ;
typedef unsigned char uint_least8_t ;
typedef unsigned short int uint_least16_t ;
typedef unsigned int uint_least32_t ;
typedef unsigned __int64 uint_least64_t ;
typedef signed int int_fast8_t ;
typedef signed int int_fast16_t ;
typedef signed int int_fast32_t ;
typedef signed __int64 int_fast64_t ;
typedef unsigned int uint_fast8_t ;
typedef unsigned int uint_fast16_t ;
typedef unsigned int uint_fast32_t ;
typedef unsigned __int64 uint_fast64_t ;
typedef signed int intptr_t ;
typedef unsigned int uintptr_t ;
typedef signed long long intmax_t ;
typedef unsigned long long uintmax_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef int ( *__heapprt ) ( void * , char const * , ... ) ;
typedef unsigned int size_t ;
typedef unsigned char mz_uint8 ;
typedef signed short mz_int16 ;
typedef unsigned short mz_uint16 ;
typedef unsigned int mz_uint32 ;
typedef unsigned int mz_uint ;
typedef int32_t mz_int64 ;
typedef int32_t mz_uint64 ;
typedef int mz_bool ;
typedef unsigned int MZ_FILE ;
typedef mz_bool ( *tdefl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef int ( *tinfl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef mz_uint32 tinfl_bit_buf_t ;
typedef size_t ( *mz_file_read_func ) ( void *pOpaque , mz_uint64 file_ofs , void *pBuf , size_t n ) ;
typedef size_t ( *mz_file_write_func ) ( void *pOpaque , mz_uint64 file_ofs , const void *pBuf , size_t n ) ;
typedef mz_bool ( *mz_file_needs_keepalive ) ( void *pOpaque ) ;
//PPC Version : V2.1.9.30
//PPL Source File Name : \tavor\Arbel\obj_PMD2NONE\prepass_results\miniz_tinfl.ppp
//PPL Source File Name : \\mbtk\\miniz\\src\\miniz_tinfl.c
typedef signed int ptrdiff_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef long double max_align_t ;
typedef unsigned long mz_ulong ;
typedef void * ( *mz_alloc_func ) ( void *opaque , size_t items , size_t size ) ;
typedef void ( *mz_free_func ) ( void *opaque , void *address ) ;
typedef void * ( *mz_realloc_func ) ( void *opaque , void *address , size_t items , size_t size ) ;
typedef mz_stream *mz_streamp ;
typedef unsigned char Byte ;
typedef unsigned int uInt ;
typedef mz_ulong uLong ;
typedef Byte Bytef ;
typedef uInt uIntf ;
typedef char charf ;
typedef int intf ;
typedef void *voidpf ;
typedef uLong uLongf ;
typedef void *voidp ;
typedef void *const voidpc ;
typedef signed char int8_t ;
typedef signed short int int16_t ;
typedef signed int int32_t ;
typedef signed __int64 int64_t ;
typedef unsigned char uint8_t ;
typedef unsigned short int uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned __int64 uint64_t ;
typedef signed char int_least8_t ;
typedef signed short int int_least16_t ;
typedef signed int int_least32_t ;
typedef signed __int64 int_least64_t ;
typedef unsigned char uint_least8_t ;
typedef unsigned short int uint_least16_t ;
typedef unsigned int uint_least32_t ;
typedef unsigned __int64 uint_least64_t ;
typedef signed int int_fast8_t ;
typedef signed int int_fast16_t ;
typedef signed int int_fast32_t ;
typedef signed __int64 int_fast64_t ;
typedef unsigned int uint_fast8_t ;
typedef unsigned int uint_fast16_t ;
typedef unsigned int uint_fast32_t ;
typedef unsigned __int64 uint_fast64_t ;
typedef signed int intptr_t ;
typedef unsigned int uintptr_t ;
typedef signed long long intmax_t ;
typedef unsigned long long uintmax_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef int ( *__heapprt ) ( void * , char const * , ... ) ;
typedef unsigned int size_t ;
typedef unsigned char mz_uint8 ;
typedef signed short mz_int16 ;
typedef unsigned short mz_uint16 ;
typedef unsigned int mz_uint32 ;
typedef unsigned int mz_uint ;
typedef int32_t mz_int64 ;
typedef int32_t mz_uint64 ;
typedef int mz_bool ;
typedef unsigned int MZ_FILE ;
typedef mz_bool ( *tdefl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef int ( *tinfl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef mz_uint32 tinfl_bit_buf_t ;
typedef size_t ( *mz_file_read_func ) ( void *pOpaque , mz_uint64 file_ofs , void *pBuf , size_t n ) ;
typedef size_t ( *mz_file_write_func ) ( void *pOpaque , mz_uint64 file_ofs , const void *pBuf , size_t n ) ;
typedef mz_bool ( *mz_file_needs_keepalive ) ( void *pOpaque ) ;
//PPC Version : V2.1.9.30
//PPL Source File Name : \tavor\Arbel\obj_PMD2NONE\prepass_results\miniz_zip.ppp
//PPL Source File Name : \\mbtk\\miniz\\src\\miniz_zip.c
typedef signed int ptrdiff_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef long double max_align_t ;
typedef unsigned long mz_ulong ;
typedef void * ( *mz_alloc_func ) ( void *opaque , size_t items , size_t size ) ;
typedef void ( *mz_free_func ) ( void *opaque , void *address ) ;
typedef void * ( *mz_realloc_func ) ( void *opaque , void *address , size_t items , size_t size ) ;
typedef mz_stream *mz_streamp ;
typedef unsigned char Byte ;
typedef unsigned int uInt ;
typedef mz_ulong uLong ;
typedef Byte Bytef ;
typedef uInt uIntf ;
typedef char charf ;
typedef int intf ;
typedef void *voidpf ;
typedef uLong uLongf ;
typedef void *voidp ;
typedef void *const voidpc ;
typedef signed char int8_t ;
typedef signed short int int16_t ;
typedef signed int int32_t ;
typedef signed __int64 int64_t ;
typedef unsigned char uint8_t ;
typedef unsigned short int uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned __int64 uint64_t ;
typedef signed char int_least8_t ;
typedef signed short int int_least16_t ;
typedef signed int int_least32_t ;
typedef signed __int64 int_least64_t ;
typedef unsigned char uint_least8_t ;
typedef unsigned short int uint_least16_t ;
typedef unsigned int uint_least32_t ;
typedef unsigned __int64 uint_least64_t ;
typedef signed int int_fast8_t ;
typedef signed int int_fast16_t ;
typedef signed int int_fast32_t ;
typedef signed __int64 int_fast64_t ;
typedef unsigned int uint_fast8_t ;
typedef unsigned int uint_fast16_t ;
typedef unsigned int uint_fast32_t ;
typedef unsigned __int64 uint_fast64_t ;
typedef signed int intptr_t ;
typedef unsigned int uintptr_t ;
typedef signed long long intmax_t ;
typedef unsigned long long uintmax_t ;
typedef unsigned int size_t ;
typedef unsigned short wchar_t ;
typedef int ( *__heapprt ) ( void * , char const * , ... ) ;
typedef unsigned int size_t ;
typedef unsigned char mz_uint8 ;
typedef signed short mz_int16 ;
typedef unsigned short mz_uint16 ;
typedef unsigned int mz_uint32 ;
typedef unsigned int mz_uint ;
typedef int32_t mz_int64 ;
typedef int32_t mz_uint64 ;
typedef int mz_bool ;
typedef unsigned int MZ_FILE ;
typedef mz_bool ( *tdefl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef int ( *tinfl_put_buf_func_ptr ) ( const void *pBuf , int len , void *pUser ) ;
typedef mz_uint32 tinfl_bit_buf_t ;
typedef size_t ( *mz_file_read_func ) ( void *pOpaque , mz_uint64 file_ofs , void *pBuf , size_t n ) ;
typedef size_t ( *mz_file_write_func ) ( void *pOpaque , mz_uint64 file_ofs , const void *pBuf , size_t n ) ;
typedef mz_bool ( *mz_file_needs_keepalive ) ( void *pOpaque ) ;
typedef unsigned int MZ_FILE ;
