//PPC Version : V2.1.9.30
//PPL Source File Name : \tavor\Arbel\obj_PMD2NONE\prepass_results\mbtk_open_hal.ppp
//PPL Source File Name : \\mbtk\\init\\mbtk_open_hal.c
typedef unsigned int size_t ;
typedef unsigned int clock_t ;
typedef unsigned int time_t ;
typedef unsigned char u8 ;
typedef unsigned short u16 ;
typedef unsigned char uint8 ;
typedef unsigned short uint16 ;
typedef unsigned int u32 ;
typedef unsigned int uint ;
typedef unsigned int uint32 ;
typedef unsigned long long u64 ;
typedef unsigned long long uint64 ;
typedef unsigned int uint_t ;
typedef unsigned char uint8_t ;
typedef unsigned short uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned long long uint64_t ;
typedef unsigned int uint_t ;
typedef unsigned char uint_8 ;
typedef unsigned short uint_16 ;
typedef unsigned int uint_32 ;
typedef unsigned long long uint_64 ;
typedef signed char int8 ;
typedef signed short int16 ;
typedef signed int int32 ;
typedef signed int int_32 ;
typedef signed long long int64 ;
typedef signed char int8_t ;
typedef signed short int16_t ;
typedef signed int int32_t ;
typedef signed long long int64_t ;
typedef unsigned char UINT8 ;
typedef unsigned short UINT16 ;
typedef unsigned int UINT ;
typedef unsigned int UINT32 ;
typedef unsigned long long UINT64 ;
typedef int INT ;
typedef char INT8 ;
typedef short INT16 ;
typedef int INT32 ;
typedef long long INT64 ;
typedef unsigned char U8 ;
typedef unsigned short U16 ;
typedef unsigned int U32 ;
typedef int S32 ;
typedef unsigned long long U64 ;
typedef char S8 ;
typedef short S16 ;
typedef long long S64 ;
typedef char s8 ;
typedef short s16 ;
typedef int s32 ;
typedef unsigned int size_t ;
typedef char ascii ;
typedef unsigned char byte ;
typedef unsigned short word ;
typedef unsigned long dword ;
typedef unsigned char BYTE ;
typedef char CHAR ;
typedef unsigned short WCHAR ;
typedef unsigned short WORD ;
typedef signed int WORD32 ;
typedef unsigned int UWORD32 ;
typedef unsigned short RESID ;
typedef float float32 ;
typedef float FLOAT ;
typedef double DOUBLE ;
typedef UINT8* PUINT8 ;
typedef INT32* PINT32 ;
typedef UINT16* PUINT16 ;
typedef INT16* PINT16 ;
typedef CHAR * PCHAR ;
typedef void* PVOID ;
typedef char * PS8 ;
typedef unsigned char * PU8 ;
typedef short * PS16 ;
typedef unsigned short * PU16 ;
typedef int * PS32 ;
typedef unsigned int * PU32 ;
typedef unsigned short pBOOL ;
typedef volatile unsigned char REG8 ;
typedef volatile unsigned short REG16 ;
typedef volatile unsigned int REG32 ;
typedef unsigned char kal_uint8 ;
typedef signed char kal_int8 ;
typedef char kal_char ;
typedef unsigned short kal_wchar ;
typedef unsigned short int kal_uint16 ;
typedef signed short int kal_int16 ;
typedef unsigned int kal_uint32 ;
typedef signed int kal_int32 ;
typedef unsigned int HRES ;
typedef unsigned int HAO ;
typedef unsigned char u8_t ;
typedef unsigned short u16_t ;
typedef u32 mbtk_mutex ;
typedef u32 mbtk_sema ;
typedef unsigned int size_t ;
typedef signed char int8_t ;
typedef signed short int int16_t ;
typedef signed int int32_t ;
typedef signed __int64 int64_t ;
typedef unsigned char uint8_t ;
typedef unsigned short int uint16_t ;
typedef unsigned int uint32_t ;
typedef unsigned __int64 uint64_t ;
typedef signed char int_least8_t ;
typedef signed short int int_least16_t ;
typedef signed int int_least32_t ;
typedef signed __int64 int_least64_t ;
typedef unsigned char uint_least8_t ;
typedef unsigned short int uint_least16_t ;
typedef unsigned int uint_least32_t ;
typedef unsigned __int64 uint_least64_t ;
typedef signed int int_fast8_t ;
typedef signed int int_fast16_t ;
typedef signed int int_fast32_t ;
typedef signed __int64 int_fast64_t ;
typedef unsigned int uint_fast8_t ;
typedef unsigned int uint_fast16_t ;
typedef unsigned int uint_fast32_t ;
typedef unsigned __int64 uint_fast64_t ;
typedef signed int intptr_t ;
typedef unsigned int uintptr_t ;
typedef signed long long intmax_t ;
typedef unsigned long long uintmax_t ;
typedef unsigned int size_t ;
typedef void* mbtk_taskref ;
typedef void* mbtk_hisrref ;
typedef void* mbtk_msgqref ;
typedef void* mbtk_mailboxqref ;
typedef void* mbtk_semref ;
typedef void* mbtk_mutexref ;
typedef void* mbtk_flagref ;
typedef void* mbtk_osmemref ;
typedef void* mbtk_ostimerref ;
typedef void *mbtk_osref ;
typedef uint8_t mbtk_os_status ;
typedef void ( *interceptor_handler_t ) ( void* client , message_data_t* msg ) ;
typedef void ( *message_handler_t ) ( void* client , message_data_t* msg ) ;
typedef void ( *reconnect_handler_t ) ( void* client , void* reconnect_date ) ;
typedef void ( *error_handler_t ) ( void *client , ol_mqtt_error_t error ) ;
typedef void ( *mqtt_callback_handler_t ) ( void* client , mqtt_cmd_id_t cmd_id , ol_mqtt_error_t error ) ;
typedef void ( *ol_acc_timer_cb ) ( unsigned int ) ;
typedef void ( * MBTK_AUDIO_PA_HOOK ) ( int enable ) ;
typedef void ( * MBTK_AUDIO_PLAYER_CALLBACK ) ( void *param ) ;
typedef void ( *MBTK_AUDIO_RECORD_CALLBACK ) ( MBTK_MCI_EVNET event , MBTK_MCI_INFO info_type , int value ) ;
typedef void ( *mbtk_mp3_play_cb ) ( int ) ;
typedef int ( *audio_process_cb ) ( char *in_buf , int in_lens , char *out_buf , int *out_lens , int samperate , int channel , int bits ) ;
typedef void ( *mbtk_amr_play_cb ) ( int ) ;
typedef void ( *audioGsmStartVoicePath_t ) ( void ) ;
typedef void ( *audioGsmStopVoicePath_t ) ( void ) ;
typedef void ( *audioGsmGetVocoderTypeRate_t ) ( unsigned short *vocoderType , unsigned short *vocoderRate ) ;
typedef char ( *audioGsmGetDtxSupport_t ) ( void ) ;
typedef void* ( *audioGsmGetTxBuffer_t ) ( void ) ;
typedef void ( *audioGsmSetAmrToc_t ) ( unsigned short ) ;
typedef void ( *audioGsmSetAmrSidTypeInd_t ) ( unsigned short ) ;
typedef void ( *audioGsmSetEncoderFlags_t ) ( unsigned short ) ;
typedef void ( *audioGsmSetDecoderSidInd_t ) ( unsigned short ) ;
typedef void ( *AUDIOHAL_HeadsetReport_T ) ( UINT32 plug , UINT32 type , UINT32 event ) ;
typedef void ( *qrcode_callback ) ( void *outdata ) ;
typedef void ( *mbtk_mp3_play_cb ) ( int ) ;
typedef void ( *mbtk_amr_play_cb ) ( int ) ;
typedef void ( *mbtk_gps_nmea ) ( char *nmea ) ;
typedef void ( *EsimMessageCallback ) ( int msg_type , const char *data , int data_len ) ;
